jobs:
- job: BuildJob
  condition: succeeded()
  displayName: 'Build package'
  steps:
  - template: python-setup.yaml
  - script: |
      cd ./transforms_sample
      python -m build

- job: UploadJob
  condition: succeeded()
  displayName: 'Upload package'
  steps:
  - template: python-setup.yaml
  - script: |
      cd ./transforms_sample
      python -m twine upload --repository-url https://pkgs.dev.azure.com/Japan-Apps-and-Infra/SOMPO-HD-DevOps/_packaging/sample-feed/pypi/upload/ --username "unused" --password $(System.AccessToken) dist/*
