jobs:
  - deployment: DeploymentJob
    variables:
      - group: ${{ parameters.variableGroupName }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: UsePythonVersion@0
              inputs:
                versionSpec: '3.8'
              displayName: 'Use Python version'
            - task: AzureWebApp@1
              displayName: 'Deploy Azure Web App'
              inputs:
                azureSubscription: 'ConnectionForDeploy'
                appName: ${{ parameters.appName }}
                package: $(Pipeline.Workspace)/drop/app.zip
                deploymentMethod: zipDeploy
                startUpCommand: 'gunicorn -b :8000 app:app'
                appSettings: |
                  -MESSAGE "${{ parameters.message }}"
