jobs:
- job: BuildAndPushImage
  displayName: 'Build and Push Docker Image'
  steps:
  - task: Docker@2
    displayName: 'Login to Azure Container Registry'
    inputs:
      command: login
      containerRegistry: $(serviceConnectionName)

  - task: Docker@2
    displayName: 'Build and Push Docker image'
    inputs:
      command: buildAndPush
      repository: $(imageName)
      dockerfile: '**/Dockerfile'
      containerRegistry: $(serviceConnectionName)
      tags: |
        $(tag)
