jobs:
- job: BuildAndPushImage
  displayName: 'Build and Push Docker Image'
  steps:
  - task: Docker@2
    displayName: 'Login to Azure Container Registry'
    inputs:
      command: login
      containerRegistry: $(CONTAINER_REGISTORY_CONNECTION_SERVICE_NAME)

  - task: Docker@2
    displayName: 'Build and Push Docker image'
    inputs:
      command: buildAndPush
      repository: $(CONTAINER_IMAGE_NAME)
      dockerfile: '**/Dockerfile'
      containerRegistry: $(CONTAINER_REGISTORY_CONNECTION_SERVICE_NAME)
      tags: |
        $(CONTAINER_IMAGE_TAG)
