stages:
- stage: Package
  condition: succeeded()
  jobs:
  - job: BuildJob
    displayName: 'Build package'
    steps:
    - script: |
        cd ./transforms_sample
        python -m build
  - job: UploadJob
    displayName: 'Upload package to Azure Artifacts'
    steps:
    - script: |
        cd ./transforms_sample
        python -m twine upload --repository-url https://pkgs.dev.azure.com/Japan-Apps-and-Infra/SOMPO-HD-DevOps/_packaging/sample-feed/pypi/upload/ --username "unused" --password $(System.AccessToken) dist/*
      displayName: 'Upload package to Azure Artifacts'
