stages:
- stage: Build
  condition: succeeded()
  jobs:
  - job: BuildJob
    displayName: 'Build package'
    steps:
    - script: |
        cd ./transforms_sample
        python -m build
- stage: Upload
  condition: succeeded()
  jobs:
  - job: UploadJob
    displayName: 'Upload package'
    steps:
    - script: |
        cd ./transforms_sample
        python -m twine upload --repository-url https://pkgs.dev.azure.com/Japan-Apps-and-Infra/SOMPO-HD-DevOps/_packaging/sample-feed/pypi/upload/ --username "unused" --password $(System.AccessToken) dist/*
