jobs:
  - job: LintJob
    displayName: 'Lint'
    steps:
      - template: python-setup.yaml
      - template: lint.yaml
  - job: UnitTestJob
    condition: succeeded()
    displayName: 'Unit test'
    steps:
      - template: python-setup.yaml
      - template: unit-test.yaml
