trigger: none
resources:
  pipelines:
    - pipeline: CI
      source: CI
      trigger:
        branches:
          - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  # 本来は CI で生成したパッケージをそのままデプロイしたいところだが、デモ用に間に合わせのジョブをつくっている状態
  - stage: GetPackage
    jobs:
      - job: GetPackageJob
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
              addToPath: true
          - script: python -m pip install --upgrade pip
            displayName: 'Upgrade pip'
          - script: pip install $(PROJECT_ROOT_DIR)
            displayName: 'Install libraries'
          - script: |
              cd $(PROJECT_ROOT_DIR)
              zip -r app.zip . -x "*.git*"
              cp ./app.zip ../
            displayName: 'Package application'
          - publish: $(System.DefaultWorkingDirectory)
            artifact: drop

  - stage: DeployToStaging
    jobs:
    - template: templates/deploy.yaml
      parameters:
        variableGroupName: 'Stg-Secrets'
        environment: 'staging'
        appName: 'egaku-staging'
        message: "$(stagingEnvMessage)"

  - stage: DeployToProduction
    jobs:
    - template: templates/deploy.yaml
      parameters:
        variableGroupName: 'Prod-Secrets'
        environment: 'production'
        appName: 'egaku-production'
        message: "$(productionEnvMessage)"
