trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  fQIN: $(CONTAINER_REGISTORY_ADDRESS)/$(CONTAINER_IMAGE_NAME):$(CONTAINER_IMAGE_TAG)

stages:
  - stage: DockerBuildAndPush
    jobs:
      - template: templates/docker-build-and-push-jobs.yaml

  - stage: Validation
    jobs:
      - template: templates/validation-jobs.yaml

  - stage: IntegrationTest
    jobs:
      - template: templates/integration-test-jobs.yaml

  - stage: BuildAndPublish
    jobs:
      - template: templates/build-and-publish-jobs.yaml

  - stage: SyncMainBranch
    jobs:
      - template: templates/sync-main-branch-jobs.yaml
