trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Integration
  jobs: 
  - job: PythonSetupJob
    displayName: 'Setup Python'
    steps:
    - template: templates/python-setup.yaml
  - template: templates/common-stages.yaml
  - template: templates/package-stages.yaml