trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Validation
    jobs:
      - template: templates/validation-jobs.yaml
  - stage: IntegrationTest
    condition: succeeded()
    jobs:
      - template: templates/integration-test-jobs.yaml
  - stage: BuildAndPublish
    condition: succeeded()
    jobs:
      - template: templates/build-and-publish-jobs.yaml
  - stage: SyncMainBranch
    condition: succeeded()
    jobs:
      - template: templates/sync-dev-branch-jobs.yaml
