trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: templates/python-setup.yaml

stages:
- template: templates/common-stages.yaml
- template: templates/package-stages.yaml