trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Integration
  steps:
  - template: templates/python-setup.yaml
  jobs:
  - template: templates/common-stages.yaml
  - template: templates/package-stages.yaml