trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
              addToPath: true
          - script: python -m pip install --upgrade pip
            displayName: 'Upgrade pip'
          - script: pip install $(PROJECT_ROOT_DIR)
            displayName: 'Install libraries'
          - script: |
              zip -r app.zip $(PROJECT_ROOT_DIR)/ -x "*.git*"
            displayName: 'Package application'
          - publish: $(System.DefaultWorkingDirectory)
            artifact: drop
  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        environment: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '3.8'
                  displayName: 'Use Python version'
                - task: AzureWebApp@1
                  displayName: 'Deploy Azure Web App : egaku'
                  inputs:
                    azureSubscription: 'ConnectionForDeploy'
                    appName: 'egaku-staging'
                    package: $(Pipeline.Workspace)/drop/app.zip
                    deploymentMethod: zipDeploy
                    startUpCommand: 'gunicorn -b :8000 app:app'
                    appSettings: |
                      -MESSAGE $(MESSAGE)
