trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
    - script: python -m pip install --upgrade pip
      displayName: 'Upgrade pip'
    - script: pip install $(PROJECT_ROOT_DIR)
      displayName: 'Install libraries'
    - script: |
        zip -r app.zip . -x "*.git*"
      displayName: 'Package application'
    - publish: $(System.DefaultWorkingDirectory)
      artifact: drop

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    environment: 'staging'
    variables:
    - group: Stg-Secrets
    steps:
    - download: current
      artifact: drop
      
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'ConnectionForDeploy'
        appType: 'webAppLinux'
        appName: 'egaku-staging'
        runtimeStack: 'PYTHON|3.8'
        package: $(Pipeline.Workspace)/drop/app.zip
        startUpCommand: 'gunicorn -b :80 app:app'
        appSettings: |
          -MESSAGE 'Hello staging!'
