trigger: none
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Validation
    jobs:
      - template: templates/validation-jobs.yaml
  - stage: SyncDevBranch
    condition: succeeded()
    jobs:
      - template: templates/sync-dev-branch-jobs.yaml
