parameters:
  - name: PROJECT_ROOT_DIR
    type: string
    default: './transforms_sample'
trigger: none
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Validation
    jobs:
      - template: templates/validation-jobs.yaml
