trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'
steps:
  - script: |
      git clone https://github.com/gitleaks/gitleaks.git
      cd gitleaks
      make build
      gitleaks detect -v
    displayName: 'Install gitleaks'
