trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'
steps:
  - script: |
    echo "Starting Gitleaks scan..."
    docker run --rm --name=gitleaks -v $(System.DefaultWorkingDirectory):/transforms_sample zricethezav/gitleaks:latest --path=/transforms_sample --no-git --verbose
  displayName: 'Install gitleaks'
