trigger:
  - main
stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Building...
            displayName: 'Build application'
  - stage: Stg
    condition: succeeded()
    variables:
      - group: Stg-Secrets
    jobs:
      - deployment: DeployToStg
        pool:
          vmImage: 'ubuntu-latest'
        environment: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo Deploying to Staging...
                    echo Using secret: $(env)
                  displayName: 'Deploy to Staging'
  - stage: DeployProd
    condition: succeeded()
    variables:
      - group: Prod-Secrets
    jobs:
      - deployment: DeployToProd
        pool:
          vmImage: 'ubuntu-latest'
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo Deploying to Production...
                    echo Using secret: $(env)
                  displayName: 'Deploy to Production'
