trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Deploy
    jobs:
      - deployment: DeployJob
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to production"
